[package]
name = "discord-bot"
version = "0.1.0"
authors = ["Timothy Cole <tim@timcole.me>"]
edition = "2018"

[dependencies]
serenity = "0.8.6"
dotenv = "0.15.0"
chrono = "0.4.11"
reqwest = "0.10.6"
tokio = { version = "0.2", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
